routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\Homepage\IndexController::class, 'index'])->name('index');
Route::get('/product', [App\Http\Controllers\Homepage\ProdukController::class, 'index'])->name('produk.index');
Route::get('/product/detail/{id}', [App\Http\Controllers\Homepage\ProdukController::class, 'detail'])->name('produk.detail');

Route::get('/cart', [App\Http\Controllers\Homepage\CartController::class, 'index'])->name('cart.index');
Route::post('/addToCart', [App\Http\Controllers\Homepage\CartController::class, 'add'])->name('cart.add');
Route::get('/cart/delete/{id}', [App\Http\Controllers\Homepage\CartController::class, 'delete'])->name('cart.delete');
Route::get('/checkout', [App\Http\Controllers\Homepage\CartController::class, 'checkout'])->name('cart.checkout');
Route::post('/checkout/add', [App\Http\Controllers\Homepage\CartController::class, 'checkout_add'])->name('cart.checkoutAdd');
Route::get('/payment', [App\Http\Controllers\Homepage\CartController::class, 'payment'])->name('cart.payment');

Route::get('/difa', [App\Http\Controllers\Homepage\DifabelController::class, 'index'])->name('difa.index');
Route::get('/difa/profil/{id}', [App\Http\Controllers\Homepage\DifabelController::class, 'profil'])->name('difa.profil');
Route::post('/difa/donasi', [App\Http\Controllers\Homepage\DifabelController::class, 'donasi'])->name('difa.donasi');

Route::get('/lowongan', [App\Http\Controllers\Homepage\LokerController::class, 'index'])->name('loker.index');
Route::get('/lowongan/detail/{id}', [App\Http\Controllers\Homepage\LokerController::class, 'detail'])->name('loker.detail');
Route::post('/lowongan/add', [App\Http\Controllers\Homepage\LokerController::class, 'add'])->name('loker.add');


//dashboard
Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard'], function () {

    Route::post('/profile/update', "ProfileController@update")->name('profile.update');
    Route::get('/invoice/transaksi/{id}', "InvoiceController@transaksi")->name('invoice.transaksi');
    Route::get('/invoice/donasi/{id}', "InvoiceController@donasi")->name('invoice.donasi');

    //admin
    Route::group(['middleware' => ['role:admin'],'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        //admin-dashboard
        Route::get('/', "DashboardController@index")->name('index');

        //admin-difabel
        Route::get('/difabel', "Difabel\DifabelController@index")->name('difabel.index');
        Route::get('/difabel/detail/{id}', "Difabel\DifabelController@detail")->name('difabel.detail');
        Route::get('/difabel/create', "Difabel\DifabelController@create")->name('difabel.create');
        Route::post('/difabel/store', "Difabel\DifabelController@store")->name('difabel.store');
        Route::post('/difabel/update', "Difabel\DifabelController@update")->name('difabel.update');
        Route::get('/difabel/produk', "Difabel\DifabelProdukController@index")->name('difabel.produk.index');
        Route::post('/difabel/produk/update/{id}', "Difabel\DifabelProdukController@update")->name('difabel.produk.update');
        Route::post('/difabel/produk/delete/{id}', "Difabel\DifabelProdukController@delete")->name('difabel.produk.delete');

        //admin-donatur
        Route::get('/donatur', "Donatur\DonaturController@index")->name('donatur.index');

        //admin-hrd
        Route::get('/hrd', "Hrd\HrdController@index")->name('hrd.index');
        //admin-hrd-loker
        Route::get('/hrd/loker', "Hrd\HrdLokerController@index")->name('hrdLoker.index');

        //admin-pembayaran
        Route::get('/pembayaran/donasi', "Pembayaran\DonasiController@index")->name('donasi.index');
        Route::post('/pembayaran/donasi/update', "Pembayaran\DonasiController@update")->name('donasi.update');
        Route::get('/pembayaran/produk', "Pembayaran\ProdukController@index")->name('produk.index');
        Route::post('/pembayaran/produk/update', "Pembayaran\ProdukController@update")->name('produk.update');

        //profile
        Route::get('/profile', "ProfileController@index")->name('profile.index');

    });


    //Hrd
    Route::group(['middleware' => ['role:hrd'],'namespace' => 'Hrd', 'prefix' => 'hrd', 'as' => 'hrd.'], function () {
        Route::get('/', "LokerController@index")->name('loker.index');
        Route::post('/loker/store', "LokerController@store")->name('loker.store');
        Route::post('/loker/update', "LokerController@update")->name('loker.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //difabel
    Route::group(['middleware' => ['role:difabel'],'namespace' => 'Difabel', 'prefix' => 'difabel', 'as' => 'difabel.'], function () {
        Route::get('/', "DashboardController@index")->name('index');

        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');

        //penjualan
        Route::get('/penjualan', "PenjualanController@index")->name('penjualan.index');

        //produk
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/store', "ProdukController@store")->name('produk.store');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');
        Route::get('/produk/delete/{id}', "ProdukController@delete")->name('produk.delete');

        //loker
        Route::get('/loker', "LokerController@index")->name('loker.index');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //donatur
    Route::group(['middleware' => ['role:donatur'],'namespace' => 'Donatur', 'prefix' => 'donatur', 'as' => 'donatur.'], function () {

        Route::get('/', "DashboardController@index")->name('index');
        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');
        Route::post('/donasi/update', "DonasiController@update")->name('donasi.update');
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

});

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;
    protected $table = 'produk';
    protected $guarded = [];

    function getDifabel()
    {
        return $this->belongsTo('App\Models\User', 'id_difabel');
    }
}

app/Http/Controllers/Dashboard/Admin/Difabel/DifabelController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use DB;

class DifabelController extends Controller
{
    public function index()
    {
        $difabel=User::role('difabel')->get();
        return view('dashboard.admin.difabel.list', compact('difabel'));
    }

    public function detail($id)
    {
        $difabel=User::find($id);
        return view('dashboard.admin.difabel.detail', compact('difabel'));
    }

    public function create()
    {
        return view('dashboard.admin.difabel.add');
    }

    public function store(Request $request)
    {
        DB::beginTransaction();

        try {
            $data=[
                'name'=>$request->name,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
                'role_id'=>2,
                'kategori_disabilitas'=>$request->kategori_disabilitas,
                'no_telp'=>$request->no_telp,
                'alamat'=>$request->alamat,
                'kota_asal'=>$request->kota_asal,
                'tanggal_lahir'=>$request->tanggal_lahir,
                'jenis_kelamin'=>$request->jenis_kelamin,
                'nama_bank'=>$request->nama_bank,
                'nomor_rekening'=>$request->nomor_rekening,
                'tentang_difabel'=>$request->tentang_difabel,
                'foto_profil'=>$request->name.'.'.$request->foto_profil->getClientOriginalExtension(),
            ];

            if ($request->hasFile('foto_profil')) {
                //upload gambar
                $file = $request->file('foto_profil');
                $patch = 'difabel';
                $name = $request->name;
                uploadImage($file, $patch, $name);
            }

            $user=User::create($data);
            $user->assignRole('difabel');


            DB::commit();
            return redirect()->route('admin.difabel.index')->with('success', 'Data berhasil ditambahkan');
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with('failed', 'Data gagal ditambahkan');
        }

    }

    public function update(Request $request)
    {
        DB::beginTransaction();

        try {
            $data=[
                'name'=>$request->name,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
                'role_id'=>2,
                'kategori_disabilitas'=>$request->kategori_disabilitas,
                'no_telp'=>$request->no_telp,
                'alamat'=>$request->alamat,
                'kota_asal'=>$request->kota_asal,
                'tanggal_lahir'=>$request->tanggal_lahir,
                'jenis_kelamin'=>$request->jenis_kelamin,
                'nama_bank'=>$request->nama_bank,
                'nomor_rekening'=>$request->nomor_rekening,
                'tentang_difabel'=>$request->tentang_difabel,
                'foto_profil'=>$request->foto_profil,
            ];

            $id=$request->id;

            $user=User::find($id)->update($data);


            DB::commit();
            return redirect()->route('admin.difabel.index')->with('success', 'Data berhasil ditambahkan');
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with('failed', 'Data gagal ditambahkan');
        }
    }
}

app/Http/Controllers/Dashboard/Admin/Difabel/DifabelProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class DifabelProdukController extends Controller
{
    public function index()
    {
        $produk=Produk::all();
        return view('dashboard.admin.difabel.produk', compact('produk'));
    }
}

app/Http/Controllers/Dashboard/Admin/Pembayaran/ProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Pembayaran;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\models\Transaksi;

class ProdukController extends Controller
{
    public function index()
    {
        $transaksi=Transaksi::all();
        return view('dashboard.admin.pembayaran.produk',compact('transaksi'));
    }

    public function update(Request $request)
    {
        $transaksi=Transaksi::find($request->id);
        $data=[
            'status'=>$request->status,
        ];
        $transaksi->update($data);
        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/Difabel/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Loker;
use App\Models\Donasi;
use App\Models\DetailTransaksi;

class DashboardController extends Controller
{
    public function index()
    {
        $id_user=auth()->user()->id;
        $donasi=Donasi::where('id_difabel',$id_user)->where('status', '1')->get();
        $penjualan = DetailTransaksi::whereHas('getProduk', function($q) use ($id_user) {
            $q->where('id_difabel', $id_user);
        })->get();

        $loker =Loker::all();

        $jmlDonasi=0;
        $jmlPenjualan=0;
        foreach ($donasi as $key => $value) {
            $jmlDonasi += $value->jumlah;
        }
        foreach ($penjualan as $key => $value) {
            $jmlPenjualan += $value->jumlah*$value->getProduk->harga;
        }

        $data = [
            'donasi' => $donasi,
            'penjualan' => $penjualan,
            'jmlDonasi' => $jmlDonasi,
            'jmlPenjualan' => $jmlPenjualan,
            'loker' => $loker,
        ];

        return view('dashboard.difabel.index', $data);
    }
}

app/Http/Controllers/Dashboard/Difabel/DonasiController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Donasi;

class DonasiController extends Controller
{
    public function index()
    {
        $donasi=Donasi::where('id_difabel', Auth()->user()->id)->where('status', "1")->get();
        return view('dashboard.difabel.donasi.list',compact('donasi'));
    }
}

app/Http/Controllers/Dashboard/Difabel/LokerController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Loker;

class LokerController extends Controller
{
    public function index()
    {
        $loker=Loker::all();
        return view('dashboard.difabel.loker.list', compact('loker'));
    }
}

app/Http/Controllers/Dashboard/Difabel/PenjualanController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\DetailTransaksi;

class PenjualanController extends Controller
{
    public function index()
    {
        $detailtransaksi=DetailTransaksi::whereHas('getProduk', function($q) {
            $q->where('id_difabel', Auth()->user()->id);
        })->get();

        return view('dashboard.difabel.penjualan.list', compact('detailtransaksi'));
    }
}

app/Http/Controllers/Dashboard/Difabel/ProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class ProdukController extends Controller
{
    public function index()
    {
        $produk=Produk::where('id_difabel', Auth()->user()->id)->get();
        return view('dashboard.difabel.produk.list', compact('produk'));
    }

    public function store(Request $request)
    {
        $data=[
            'nama_produk'=>$request->nama_produk,
            'id_difabel'=>Auth()->user()->id,
            'deskripsi_produk'=>$request->deskripsi_produk,
            'harga'=>$request->harga,
            'jumlah'=>$request->jumlah,
            'status'=>$request->status,
            'gambar_produk' => $request->nama_produk.'.'.$request->gambar_produk->getClientOriginalExtension(),
        ];

        if ($request->hasFile('gambar_produk')) {
            //upload gambar
            $file = $request->file('gambar_produk');
            $patch = 'produk';
            $name = $request->nama_produk;
            uploadImage($file, $patch, $name);
        }

        Produk::create($data);

        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/Difabel/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class ProfileController extends Controller
{
    public function index()
    {
        $user = User::find(auth()->user()->id);
        return view('dashboard.difabel.profile.index', compact('user'));
    }
}

app/Http/Controllers/Dashboard/Donatur/ProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Donatur;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Transaksi;
use App\Models\DetailTransaksi;

class ProdukController extends Controller
{
    public function index()
    {
        $pembelian=DetailTransaksi::whereHas('getTransaksi', function($q) {
            $q->where('id_user', Auth()->user()->id);
        })->get();

        $jmlPembelian=0;
        foreach ($pembelian as $key => $value) {
            $jmlPembelian += $value->jumlah*$value->getProduk->harga;
        }

        $data = [
            'pembelian' => $pembelian,
            'jmlPembelian' => $jmlPembelian,
        ];

        return view('dashboard.donatur.pembayaran.produk', $data);
    }

    public function update(Request $request)
    {
        $donasi=Transaksi::find($request->id);
        $file=$request->file('foto');
        $path="foto_pembayaran_produk/";
        $name=time()."_".$file->getClientOriginalName();
        uploadImage($file, $path, $name);

        $donasi->update([
            'bukti_pembayaran' => $name,
        ]);

        return redirect()->back();
    }

}

app/Http/Controllers/Homepage/ProdukController.php
<?php

namespace App\Http\Controllers\Homepage;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class ProdukController extends Controller
{
    public function index()
    {
        $produk = Produk::all();
        return view('homepage.produk.index', compact('produk'));
    }

    public function detail($id)
    {
        $produk = Produk::all();
        $produkDetail = Produk::find($id);
        return view('homepage.produk.detail', compact('produk','produkDetail'));
    }
}

resources/views/dashboard/difabel/produk/list.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="my-4">
            <h2>Halaman <strong><span class="text-primary">List Produk</span></strong></h2>
            <br>
            <a href="javascript:void(0)" data-toggle="modal" data-target="#modalAddProduk">
                <button class="btn btn-primary">Tambah Produk</button>
            </a>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <br>
            <div class="table-overflow container">
                <table class="table table-striped table-bordered datatable">
                    <thead>
                        <tr>
                            <th>Nama Produk</th>
                            <th>Jumlah</th>
                            <th>Harga</th>
                            <th>Deskripsi</th>
                            <th>Status</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($produk as $item)
                        <tr>
                            <td>
                                <div class="list-media">
                                    <div class="list-item">
                                        <div class="media-img">
                                            <img src="{{ asset('produk/'.$item->gambar_produk)}}" alt="">
                                        </div>
                                        <div class="info">
                                            <span class="title">{{$item->nama_produk}}</span>
                                            <span class="sub-title">ID {{$item->id}}</span>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>{{$item->jumlah}}</td>
                            <td>Rp. {{$item->harga}}</td>
                            <td width="30%">{{$item->deskripsi_produk}}</td>
                            <td><span class="badge badge-pill badge-primary">
                                @if($item->status == 0){
                                    <span class="text-semibold">Non Aktif</span>
                                @else
                                    <span class="text-semibold">Aktif</span>
                                @endif
                            </span></td>
                            <td class="text-center font-size-18">
                                <a href="javascript:void(0)" data-toggle="modal" data-target="#modalCekProduk{{$item->id}}"
                                    class="text-gray m-r-15"><i class="ti-pencil"></i></a>
                                <a href="" class="text-gray"><i class="ti-trash"></i></a>
                            </td>
                        </tr>

                        <!-- Modal Cek Produk-->
                        <div class="modal fade" id="modalCekProduk{{$item->id}}">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4>Detail Produk</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-sm-12">
                                                    <div class="form-row">
                                                        <div class="form-group col-md-9">
                                                            <label class="control-label">Nama Produk</label>
                                                            <input type="text" name="nama_produk" class="form-control"
                                                                value="{{$item->nama_produk}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-12">
                                                            <label class="control-label">Deskripsi Produk</label>
                                                            <textarea class="form-control" name="deskripsi_produk"
                                                                rows="3">{{$item->deskripsi_produk}}</textarea>
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                            <label class="control-label">Jumlah</label>
                                                            <input type="number" value="{{ $item->jumlah }}" name="jumlah" class="form-control" value="11">
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label class="control-label">Harga</label>
                                                            <input type="number" class="form-control" value="{{ $item->harga }}" name="harga">
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                            <label class="control-label">Gambar</label>
                                                            <input type="file" name="gambar_produk" class="form-control">
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <img src="{{ asset('produk/'.$item->gambar_produk)}}" width="40%">
                                                        </div>
                                                    </div>

                                                    <div class="form-row">
                                                        <div class="form-group col-md-12">
                                                            <label class="control-label">Status</label>
                                                            <select class="form-control" name="status">
                                                                <option value="1">Aktif</option>
                                                                <option value="0">Non-Aktif</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="col-sm-12">
                                                            <div class="text-center">
                                                                <a href="{{ route('difabel.produk.delete', [$item->id])}}" class="btn btn-gradient-danger btn-full">Hapus
                                                                    Produk</a>
                                                                <button type="submit"
                                                                    class="btn btn-gradient-success btn-full">Konfirmasi
                                                                    Perubahan</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


<!-- Modal Add Produk-->
<div class="modal fade" id="modalAddProduk">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Tambah Produk</h4>
            </div>
            <div class="modal-body">
                <div class="card-body">
                    <form action="{{ route('difabel.produk.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label">Nama Produk</label>
                                        <input type="text" name="nama_produk" class="form-control" value="">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label">Deskripsi Produk</label>
                                        <textarea class="form-control" name="deskripsi_produk" rows="3"></textarea>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label class="control-label">Jumlah</label>
                                        <input type="number" name="jumlah" class="form-control" value="">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label class="control-label">Harga</label>
                                        <input type="number" name="harga" class="form-control" value="">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label class="control-label">Gambar</label>
                                        <input type="file" name="gambar_produk" class="form-control">
                                    </div>
                                    <div class="form-group col-md-6">
                                        <img src="" width="40%">
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="form-group col-md-12">
                                        <label class="control-label">Status</label>
                                        <select class="form-control" name="status">
                                            <option value="1">Aktif</option>
                                            <option value="0">Non-Aktif</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-sm-12">
                                        <div class="text-center">
                                            <button
                                                class="btn btn-danger btn-full">Batalkan</button>
                                            <button type="submit" class="btn btn-primary btn-full">Simpan
                                                Produk</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection