routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\Homepage\IndexController::class, 'index'])->name('index');
Route::get('/product', [App\Http\Controllers\Homepage\ProdukController::class, 'index'])->name('produk.index');
Route::get('/product/detail/{id}', [App\Http\Controllers\Homepage\ProdukController::class, 'detail'])->name('produk.detail');

Route::get('/cart', [App\Http\Controllers\Homepage\CartController::class, 'index'])->name('cart.index');
Route::post('/addToCart', [App\Http\Controllers\Homepage\CartController::class, 'add'])->name('cart.add');
Route::get('/cart/delete/{id}', [App\Http\Controllers\Homepage\CartController::class, 'delete'])->name('cart.delete');
Route::get('/checkout', [App\Http\Controllers\Homepage\CartController::class, 'checkout'])->name('cart.checkout');
Route::post('/checkout/add', [App\Http\Controllers\Homepage\CartController::class, 'checkout_add'])->name('cart.checkoutAdd');
Route::get('/payment', [App\Http\Controllers\Homepage\CartController::class, 'payment'])->name('cart.payment');

Route::get('/difa', [App\Http\Controllers\Homepage\DifabelController::class, 'index'])->name('difa.index');
Route::get('/difa/profil/{id}', [App\Http\Controllers\Homepage\DifabelController::class, 'profil'])->name('difa.profil');
Route::post('/difa/donasi', [App\Http\Controllers\Homepage\DifabelController::class, 'donasi'])->name('difa.donasi');

Route::get('/lowongan', [App\Http\Controllers\Homepage\LokerController::class, 'index'])->name('loker.index');
Route::get('/lowongan/detail/{id}', [App\Http\Controllers\Homepage\LokerController::class, 'detail'])->name('loker.detail');
Route::post('/lowongan/add', [App\Http\Controllers\Homepage\LokerController::class, 'add'])->name('loker.add');


//dashboard
Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard'], function () {

    Route::post('/profile/update', "ProfileController@update")->name('profile.update');
    Route::get('/invoice/transaksi/{id}', "InvoiceController@transaksi")->name('invoice.transaksi');
    Route::get('/invoice/donasi/{id}', "InvoiceController@donasi")->name('invoice.donasi');

    //admin
    Route::group(['middleware' => ['role:admin'],'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        //admin-dashboard
        Route::get('/', "DashboardController@index")->name('index');

        //admin-difabel
        Route::get('/difabel', "Difabel\DifabelController@index")->name('difabel.index');
        Route::get('/difabel/detail/{id}', "Difabel\DifabelController@detail")->name('difabel.detail');
        Route::get('/difabel/create', "Difabel\DifabelController@create")->name('difabel.create');
        Route::post('/difabel/store', "Difabel\DifabelController@store")->name('difabel.store');
        Route::post('/difabel/update', "Difabel\DifabelController@update")->name('difabel.update');
        Route::get('/difabel/produk', "Difabel\DifabelProdukController@index")->name('difabel.produk.index');
        Route::post('/difabel/produk/update/{id}', "Difabel\DifabelProdukController@update")->name('difabel.produk.update');
        Route::post('/difabel/produk/delete/{id}', "Difabel\DifabelProdukController@delete")->name('difabel.produk.delete');

        //admin-donatur
        Route::get('/donatur', "Donatur\DonaturController@index")->name('donatur.index');

        //admin-hrd
        Route::get('/hrd', "Hrd\HrdController@index")->name('hrd.index');
        //admin-hrd-loker
        Route::get('/hrd/loker', "Hrd\HrdLokerController@index")->name('hrdLoker.index');

        //admin-pembayaran
        Route::get('/pembayaran/donasi', "Pembayaran\DonasiController@index")->name('donasi.index');
        Route::post('/pembayaran/donasi/update', "Pembayaran\DonasiController@update")->name('donasi.update');
        Route::get('/pembayaran/produk', "Pembayaran\ProdukController@index")->name('produk.index');
        Route::post('/pembayaran/produk/update', "Pembayaran\ProdukController@update")->name('produk.update');

        //profile
        Route::get('/profile', "ProfileController@index")->name('profile.index');

    });


    //Hrd
    Route::group(['middleware' => ['role:hrd'],'namespace' => 'Hrd', 'prefix' => 'hrd', 'as' => 'hrd.'], function () {
        Route::get('/', "LokerController@index")->name('loker.index');
        Route::post('/loker/store', "LokerController@store")->name('loker.store');
        Route::post('/loker/update', "LokerController@update")->name('loker.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //difabel
    Route::group(['middleware' => ['role:difabel'],'namespace' => 'Difabel', 'prefix' => 'difabel', 'as' => 'difabel.'], function () {
        Route::get('/', "DashboardController@index")->name('index');

        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');

        //penjualan
        Route::get('/penjualan', "PenjualanController@index")->name('penjualan.index');

        //produk
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/store', "ProdukController@store")->name('produk.store');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');
        Route::get('/produk/delete/{id}', "ProdukController@delete")->name('produk.delete');

        //loker
        Route::get('/loker', "LokerController@index")->name('loker.index');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //donatur
    Route::group(['middleware' => ['role:donatur'],'namespace' => 'Donatur', 'prefix' => 'donatur', 'as' => 'donatur.'], function () {

        Route::get('/', "DashboardController@index")->name('index');
        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');
        Route::post('/donasi/update', "DonasiController@update")->name('donasi.update');
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

});

app/Http/Controllers/Dashboard/Admin/Difabel/DifabelController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use DB;

class DifabelController extends Controller
{
    public function index()
    {
        $difabel=User::role('difabel')->get();
        return view('dashboard.admin.difabel.list', compact('difabel'));
    }

    public function detail($id)
    {
        $difabel=User::find($id);
        return view('dashboard.admin.difabel.detail', compact('difabel'));
    }

    public function create()
    {
        return view('dashboard.admin.difabel.add');
    }

    public function store(Request $request)
    {
        DB::beginTransaction();

        try {
            $data=[
                'name'=>$request->name,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
                'role_id'=>2,
                'kategori_disabilitas'=>$request->kategori_disabilitas,
                'no_telp'=>$request->no_telp,
                'alamat'=>$request->alamat,
                'kota_asal'=>$request->kota_asal,
                'tanggal_lahir'=>$request->tanggal_lahir,
                'jenis_kelamin'=>$request->jenis_kelamin,
                'nama_bank'=>$request->nama_bank,
                'nomor_rekening'=>$request->nomor_rekening,
                'tentang_difabel'=>$request->tentang_difabel,
                'foto_profil'=>$request->name.'.'.$request->foto_profil->getClientOriginalExtension(),
            ];

            if ($request->hasFile('foto_profil')) {
                //upload gambar
                $file = $request->file('foto_profil');
                $patch = 'difabel';
                $name = $request->name;
                uploadImage($file, $patch, $name);
            }

            $user=User::create($data);
            $user->assignRole('difabel');


            DB::commit();
            return redirect()->route('admin.difabel.index')->with('success', 'Data berhasil ditambahkan');
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with('failed', 'Data gagal ditambahkan');
        }

    }

    public function update(Request $request)
    {
        DB::beginTransaction();

        try {
            $data=[
                'name'=>$request->name,
                'email'=>$request->email,
                'password'=>bcrypt($request->password),
                'role_id'=>2,
                'kategori_disabilitas'=>$request->kategori_disabilitas,
                'no_telp'=>$request->no_telp,
                'alamat'=>$request->alamat,
                'kota_asal'=>$request->kota_asal,
                'tanggal_lahir'=>$request->tanggal_lahir,
                'jenis_kelamin'=>$request->jenis_kelamin,
                'nama_bank'=>$request->nama_bank,
                'nomor_rekening'=>$request->nomor_rekening,
                'tentang_difabel'=>$request->tentang_difabel,
                'foto_profil'=>$request->foto_profil,
            ];

            $id=$request->id;

            $user=User::find($id)->update($data);


            DB::commit();
            return redirect()->route('admin.difabel.index')->with('success', 'Data berhasil ditambahkan');
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->with('failed', 'Data gagal ditambahkan');
        }
    }
}

app/Http/Controllers/Dashboard/Admin/Difabel/DifabelProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class DifabelProdukController extends Controller
{
    public function index()
    {
        $produk=Produk::all();
        return view('dashboard.admin.difabel.produk', compact('produk'));
    }
}

app/Http/Controllers/Dashboard/Difabel/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Loker;
use App\Models\Donasi;
use App\Models\DetailTransaksi;

class DashboardController extends Controller
{
    public function index()
    {
        $id_user=auth()->user()->id;
        $donasi=Donasi::where('id_difabel',$id_user)->where('status', '1')->get();
        $penjualan = DetailTransaksi::whereHas('getProduk', function($q) use ($id_user) {
            $q->where('id_difabel', $id_user);
        })->get();

        $loker =Loker::all();

        $jmlDonasi=0;
        $jmlPenjualan=0;
        foreach ($donasi as $key => $value) {
            $jmlDonasi += $value->jumlah;
        }
        foreach ($penjualan as $key => $value) {
            $jmlPenjualan += $value->jumlah*$value->getProduk->harga;
        }

        $data = [
            'donasi' => $donasi,
            'penjualan' => $penjualan,
            'jmlDonasi' => $jmlDonasi,
            'jmlPenjualan' => $jmlPenjualan,
            'loker' => $loker,
        ];

        return view('dashboard.difabel.index', $data);
    }
}

app/Http/Controllers/Dashboard/Difabel/DonasiController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Donasi;

class DonasiController extends Controller
{
    public function index()
    {
        $donasi=Donasi::where('id_difabel', Auth()->user()->id)->where('status', "1")->get();
        return view('dashboard.difabel.donasi.list',compact('donasi'));
    }
}

app/Http/Controllers/Dashboard/Difabel/LokerController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Loker;

class LokerController extends Controller
{
    public function index()
    {
        $loker=Loker::all();
        return view('dashboard.difabel.loker.list', compact('loker'));
    }
}

app/Http/Controllers/Dashboard/Difabel/PenjualanController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\DetailTransaksi;

class PenjualanController extends Controller
{
    public function index()
    {
        $detailtransaksi=DetailTransaksi::whereHas('getProduk', function($q) {
            $q->where('id_difabel', Auth()->user()->id);
        })->get();

        return view('dashboard.difabel.penjualan.list', compact('detailtransaksi'));
    }
}

app/Http/Controllers/Dashboard/Difabel/ProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;

class ProdukController extends Controller
{
    public function index()
    {
        $produk=Produk::where('id_difabel', Auth()->user()->id)->get();
        return view('dashboard.difabel.produk.list', compact('produk'));
    }

    public function store(Request $request)
    {
        $data=[
            'nama_produk'=>$request->nama_produk,
            'id_difabel'=>Auth()->user()->id,
            'deskripsi_produk'=>$request->deskripsi_produk,
            'harga'=>$request->harga,
            'jumlah'=>$request->jumlah,
            'status'=>$request->status,
            'gambar_produk' => $request->nama_produk.'.'.$request->gambar_produk->getClientOriginalExtension(),
        ];

        if ($request->hasFile('gambar_produk')) {
            //upload gambar
            $file = $request->file('gambar_produk');
            $patch = 'produk';
            $name = $request->nama_produk;
            uploadImage($file, $patch, $name);
        }

        Produk::create($data);

        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/Difabel/ProfileController.php
<?php

namespace App\Http\Controllers\Dashboard\Difabel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;

class ProfileController extends Controller
{
    public function index()
    {
        $user = User::find(auth()->user()->id);
        return view('dashboard.difabel.profile.index', compact('user'));
    }
}

app/Http/Controllers/Homepage/DifabelController.php
<?php

namespace App\Http\Controllers\Homepage;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Produk;
use App\Models\Donasi;

class DifabelController extends Controller
{
    public function index()
    {
        $difabel = User::role('difabel')->get();
        return view('homepage.difabel.list', compact('difabel'));
    }

    public function profil($id)
    {
        $difabel = User::role('difabel')->findOrFail($id);
        $produk = Produk::where('id_difabel', $id)->get();
        return view('homepage.difabel.profil', compact('difabel', 'produk'));
    }

    public function donasi(Request $request)
    {
        $data=[
            'id_difabel' => $request->id_difabel,
            'id_donatur' => auth()->user()->id,
            'jumlah' => $request->jumlah,
            'pesan_semangat' => $request->pesan_semangat,
            'status' => '0',
        ];

        $total=$request->jumlah;
        Donasi::create($data);
        return view('homepage.cart.payment', compact('total'));
    }
}

resources/views/dashboard/admin/difabel/add.blade.php
@extends('layouts.dashboard')

@section('content')
<form action="{{ route('admin.difabel.store')}}" method="POST" enctype="multipart/form-data">
    @csrf
<div class="row">
    <h2>Informasi Lengkap</h2>
    <br>
        <div class="col-sm-12 mt-4">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="control-label">Nama Lengkap</label>
                    <input type="text" name="name" class="form-control">
                </div>
                <div class="form-group col-md-6">
                    <label class="control-label">Kategori Disabilitas</label>
                    <select class="form-control" name="kategori_disabilitas">
                        <option selected disabled>-</option>
                        <option value="Disabilitas fisik">Disabilitas fisik</option>
                        <option value="Disabilitas sensorik">Disabilitas sensorik</option>
                        <option value="Disabilitas mental">Disabilitas mental</option>
                        <option value="Disabilitas intelektual">Disabilitas intelektual</option>
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    <label class="control-label">Email</label>
                    <input type="email" name="email" class="form-control">
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Password</label>
                    <input type="password" name="password" class="form-control">
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">No. Telp</label>
                    <input type="number" name="no_telp" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <label class="control-label">Alamat</label>
                    <input type="text" name="alamat" class="form-control">
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Asal Kota</label>
                    <input type="text" name="kota_asal" class="form-control">
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Tanggal Lahir</label>
                    <input type="date" name="tanggal_lahir" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-3">
                    <label class="control-label">Jenis Kelamin</label>
                    <select name="jenis_kelamin" class="form-control">
                        <option>-</option>
                        <option value="L">Laki - Laki</option>
                        <option value="P">Perempuan</option>
                    </select>
                </div>
                <div class="form-group col-md-4">
                    <label class="control-label">Nama Bank</label>
                    <select name="nama_bank" class="form-control">
                        <option>-</option>
                        <option value="BCA">BCA</option>
                        <option value="BNI">BNI</option>
                        <option value="BRI">BRI</option>
                        <option value="Mandiri">Mandiri</option>
                        <option value="BTN">BTN</option>
                        <option value="Permata">Permata</option>
                    </select>
                </div>
                <div class="form-group col-md-5">
                    <label class="control-label">No. Rekening</label>
                    <input type="number" name="nomor_rekening" class="form-control">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-7">
                    <label class="control-label">Tentang Difabel</label>
                    <textarea name="tentang_difabel" class="form-control" rows="6"></textarea>
                </div>
                <div class="form-group col-md-5">
                    <label class="control-label">Upload foto profil</label>
                    <input type="file" name="foto_profil" class="form-control">
                </div>
            </div>

            <div class="form-row">
                <div class="col-sm-6">
                    <div class="form-group">
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="text-sm-right">
                        <button class="btn btn-gradient-success">TAMBAH DATA</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/dashboard/admin/difabel/detail.blade.php
@extends('layouts.dashboard')

@section('content')
<form action="{{ route('admin.difabel.update')}}" method="POST" enctype="multipart/form-data">
@csrf
<input type="hidden" name="id" value="{{ $difabel['id'] }}">
<div class="row">
    <h2>Informasi Lengkap</h2>
    <br>
    <div class="col-sm-12 mt-4">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label class="control-label">Nama Lengkap</label>
                <input type="text" name="name" value="{{$difabel['name']}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Email</label>
                <input type="email" name="email" value="{{$difabel['email']}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">No. Telp</label>
                <input type="number" name="no_telp" value="{{$difabel['no_telp']}}" class="form-control">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-5">
                <label class="control-label">Alamat</label>
                <input type="text" name="alamat" value="{{$difabel['alamat']}}" class="form-control">
            </div>
            <div class="form-group col-md-4">
                <label class="control-label">Asal Kota</label>
                <input type="text" name="kota_asal" value="{{$difabel['kota_asal']}}" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Tanggal Lahir</label>
                <input type="date" name="tanggal_lahir" value="{{$difabel['tanggal_lahir']}}" class="form-control">
            </div>
        </div>
        <div class="form-group">

        </div>
        <div class="form-group">
            <label class="control-label">Tentang Difabel</label>
            <textarea class="form-control" name="tentang_difabel" rows="6">{{$difabel['tentang_difabel']}}</textarea>
        </div>
        <div class="form-row">
            <div class="form-group col-md-5">
                <label class="control-label">Total Donasi</label>
                <input type="number" class="form-control">
            </div>
            <div class="form-group col-md-4">
                <label class="control-label">Total Produk</label>
                <input type="number" class="form-control">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Status</label>
                <?php
                $aktif="";
                    $nonaktif="";
                    if ($difabel['status']=="0") {
                        $nonaktif="selected";
                    }
                    else{
                        $aktif="selected";
                    }
                ?>
                <select class="form-control">
                    <option {{$aktif}}>Aktif</option>
                    <option {{$nonaktif}}>Non-Aktif</option>
                </select>
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-6">
                <div class="form-group">

                </div>
            </div>
            <div class="col-sm-6">
                <div class="text-sm-right">
                    <button class="btn btn-gradient-success">SIMPAN PERUBAHAN</button>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
@endsection

resources/views/dashboard/admin/difabel/list.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">List Difabel</h4>
            </div>
            <div class="table-overflow container">
                <table class="table table-striped table-bordered datatable">
                    <thead>
                        <tr>
                            <td class="text-dark text-semibold">Nama</td>
                            <td class="text-dark text-semibold">Tanggal Lahir</td>
                            <td class="text-dark text-semibold">Kota Asal</td>
                            <td class="text-dark text-semibold">Email</td>
                            <td class="text-dark text-semibold">No. Telp</td>
                            <td class="text-dark text-semibold">Total Donasi</td>
                            <td class="text-dark text-semibold">Status</td>
                            <td class="text-dark text-semibold">Aksi</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($difabel as $item)
                        <tr>
                            <td>
                                <div class="list-item">
                                    <div class="info">
                                        <span class="title p-t-10 text-semibold">{{ $item->name }}</span>
                                    </div>
                                </div>
                            </td>
                            <td> {{ $item->tanggal_lahir }} </td>
                            <td> {{ $item->kota_asal }}</td>
                            <td> {{ $item->email }}</td>
                            <td> {{ $item->no_telp }}</td>
                            <td><span class="text-primary"><strong>Rp. {{$item->getDonasi->where('status','1')->sum('jumlah')}}</strong></span>
                            </td>
                            <td><span class="badge badge-pill badge-primary">Aktif</span></td>
                            <td>
                                <a href="{{ route('admin.difabel.detail', ['id' => $item->id])}}">
                                    <button
                                        class="btn btn-icon btn-gradient-success mt-3 btn-sm">
                                        <i class="mdi mdi-eye"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/admin/difabel/produk.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Semua Produk Difabel</h4>
            </div>
            <div class="table-overflow container">
                <table class="table table-striped table-bordered datatable">
                    <thead>
                        <tr>
                            <td class="text-dark text-semibold">ID</td>
                            <td class="text-dark text-semibold">Nama Produk</td>
                            <td class="text-dark text-semibold">Oleh</td>
                            <td class="text-dark text-semibold">Deskripsi</td>
                            <td class="text-dark text-semibold">Jumlah</td>
                            <td class="text-dark text-semibold">Harga</td>
                            <td class="text-dark text-semibold">Status</td>
                            <td class="text-dark text-semibold">Aksi</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($produk as $item)
                            <tr>
                            <td>{{ $item->id }}</td>
                            <td>
                                <div class="list-item">
                                    <div class="info">
                                        <span class="title p-t-10 text-semibold">{{ $item->nama_produk }}</span>
                                    </div>
                                </div>
                            </td>
                            <td> {{ $item->getDifabel->name }} </td>
                            <td> {{ $item->deskripsi_produk }} </td>
                            <td> 11</td>
                            <td><span class="text-primary"><strong>{{ $item->harga }}</strong></span></td>
                            <td><span class="badge badge-pill badge-primary">Aktif</span></td>
                            <td>
                                <a href="javascript:void(0)" data-toggle="modal" data-target="#modalCekProduk">
                                    <button class="btn btn-icon btn-gradient-success mt-3 btn-sm">
                                        <i class="mdi mdi-eye"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection