routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/home', function () {
    return redirect('/');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/', [App\Http\Controllers\Homepage\IndexController::class, 'index'])->name('index');
Route::get('/product', [App\Http\Controllers\Homepage\ProdukController::class, 'index'])->name('produk.index');
Route::get('/product/detail/{id}', [App\Http\Controllers\Homepage\ProdukController::class, 'detail'])->name('produk.detail');

Route::get('/cart', [App\Http\Controllers\Homepage\CartController::class, 'index'])->name('cart.index');
Route::post('/addToCart', [App\Http\Controllers\Homepage\CartController::class, 'add'])->name('cart.add');
Route::get('/cart/delete/{id}', [App\Http\Controllers\Homepage\CartController::class, 'delete'])->name('cart.delete');
Route::get('/checkout', [App\Http\Controllers\Homepage\CartController::class, 'checkout'])->name('cart.checkout');
Route::post('/checkout/add', [App\Http\Controllers\Homepage\CartController::class, 'checkout_add'])->name('cart.checkoutAdd');
Route::get('/payment', [App\Http\Controllers\Homepage\CartController::class, 'payment'])->name('cart.payment');

Route::get('/difa', [App\Http\Controllers\Homepage\DifabelController::class, 'index'])->name('difa.index');
Route::get('/difa/profil/{id}', [App\Http\Controllers\Homepage\DifabelController::class, 'profil'])->name('difa.profil');
Route::post('/difa/donasi', [App\Http\Controllers\Homepage\DifabelController::class, 'donasi'])->name('difa.donasi');

Route::get('/lowongan', [App\Http\Controllers\Homepage\LokerController::class, 'index'])->name('loker.index');
Route::get('/lowongan/detail/{id}', [App\Http\Controllers\Homepage\LokerController::class, 'detail'])->name('loker.detail');
Route::post('/lowongan/add', [App\Http\Controllers\Homepage\LokerController::class, 'add'])->name('loker.add');


//dashboard
Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard'], function () {

    Route::post('/profile/update', "ProfileController@update")->name('profile.update');
    Route::get('/invoice/transaksi/{id}', "InvoiceController@transaksi")->name('invoice.transaksi');
    Route::get('/invoice/donasi/{id}', "InvoiceController@donasi")->name('invoice.donasi');

    //admin
    Route::group(['middleware' => ['role:admin'],'namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        //admin-dashboard
        Route::get('/', "DashboardController@index")->name('index');

        //admin-difabel
        Route::get('/difabel', "Difabel\DifabelController@index")->name('difabel.index');
        Route::get('/difabel/detail/{id}', "Difabel\DifabelController@detail")->name('difabel.detail');
        Route::get('/difabel/create', "Difabel\DifabelController@create")->name('difabel.create');
        Route::post('/difabel/store', "Difabel\DifabelController@store")->name('difabel.store');
        Route::post('/difabel/update', "Difabel\DifabelController@update")->name('difabel.update');
        Route::get('/difabel/produk', "Difabel\DifabelProdukController@index")->name('difabel.produk.index');
        Route::post('/difabel/produk/update/{id}', "Difabel\DifabelProdukController@update")->name('difabel.produk.update');
        Route::post('/difabel/produk/delete/{id}', "Difabel\DifabelProdukController@delete")->name('difabel.produk.delete');

        //admin-donatur
        Route::get('/donatur', "Donatur\DonaturController@index")->name('donatur.index');

        //admin-hrd
        Route::get('/hrd', "Hrd\HrdController@index")->name('hrd.index');
        //admin-hrd-loker
        Route::get('/hrd/loker', "Hrd\HrdLokerController@index")->name('hrdLoker.index');

        //admin-pembayaran
        Route::get('/pembayaran/donasi', "Pembayaran\DonasiController@index")->name('donasi.index');
        Route::post('/pembayaran/donasi/update', "Pembayaran\DonasiController@update")->name('donasi.update');
        Route::get('/pembayaran/produk', "Pembayaran\ProdukController@index")->name('produk.index');
        Route::post('/pembayaran/produk/update', "Pembayaran\ProdukController@update")->name('produk.update');

        //profile
        Route::get('/profile', "ProfileController@index")->name('profile.index');

    });


    //Hrd
    Route::group(['middleware' => ['role:hrd'],'namespace' => 'Hrd', 'prefix' => 'hrd', 'as' => 'hrd.'], function () {
        Route::get('/', "LokerController@index")->name('loker.index');
        Route::post('/loker/store', "LokerController@store")->name('loker.store');
        Route::post('/loker/update', "LokerController@update")->name('loker.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //difabel
    Route::group(['middleware' => ['role:difabel'],'namespace' => 'Difabel', 'prefix' => 'difabel', 'as' => 'difabel.'], function () {
        Route::get('/', "DashboardController@index")->name('index');

        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');

        //penjualan
        Route::get('/penjualan', "PenjualanController@index")->name('penjualan.index');

        //produk
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/store', "ProdukController@store")->name('produk.store');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');
        Route::get('/produk/delete/{id}', "ProdukController@delete")->name('produk.delete');

        //loker
        Route::get('/loker', "LokerController@index")->name('loker.index');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

    //donatur
    Route::group(['middleware' => ['role:donatur'],'namespace' => 'Donatur', 'prefix' => 'donatur', 'as' => 'donatur.'], function () {

        Route::get('/', "DashboardController@index")->name('index');
        //donasi
        Route::get('/donasi', "DonasiController@index")->name('donasi.index');
        Route::post('/donasi/update', "DonasiController@update")->name('donasi.update');
        Route::get('/produk', "ProdukController@index")->name('produk.index');
        Route::post('/produk/update', "ProdukController@update")->name('produk.update');

        Route::get('/profile', "ProfileController@index")->name('profile.index');
    });

});

app/Http/Controllers/Dashboard/Admin/Pembayaran/DonasiController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Pembayaran;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Donasi;

class DonasiController extends Controller
{
    public function index()
    {
        $donasi=Donasi::all();
        return view('dashboard.admin.pembayaran.donasi', compact('donasi'));
    }

    public function update(Request $request)
    {
        $donasi=Donasi::find($request->id);
        $data=[
            'status'=>$request->status,
        ];
        $donasi->update($data);
        return redirect()->back();
    }
};

app/Http/Controllers/Dashboard/Admin/Pembayaran/ProdukController.php
<?php

namespace App\Http\Controllers\Dashboard\Admin\Pembayaran;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\models\Transaksi;

class ProdukController extends Controller
{
    public function index()
    {
        $transaksi=Transaksi::all();
        return view('dashboard.admin.pembayaran.produk',compact('transaksi'));
    }

    public function update(Request $request)
    {
        $transaksi=Transaksi::find($request->id);
        $data=[
            'status'=>$request->status,
        ];
        $transaksi->update($data);
        return redirect()->back();
    }
}

resources/views/dashboard/admin/pembayaran/donasi.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Donasi Terbaru</h4>
            </div>
            <div class="table-overflow container">
                <table class="table table-striped table-bordered datatable">
                    <thead>
                        <tr>
                            <td class="text-dark text-semibold">Nama User</td>
                            <td class="text-dark text-semibold">Order ID</td>
                            <td class="text-dark text-semibold">Tgl Masuk</td>
                            <td class="text-dark text-semibold">Jumlah</td>
                            <td class="text-dark text-semibold">Status</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($donasi as $item)
                        <tr>
                            <td>
                                <div class="list-item">
                                    <div class="info">
                                        <span class="title p-t-10 text-semibold">{{$item->getDonatur->name}}</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:void(0)" data-toggle="modal" data-target="#modalCekPembayaran{{$item->id}}">
                                    #{{$item->id}}
                                </a>
                            </td>
                            <td>{{$item->tanggal_bayar}}</td>
                            <td>{{$item->jumlah}}</td>
                            <td><span class="badge badge-pill ">
                                @if ($item->status == 0)
                                Pending
                                @else
                                Diterima
                                @endif
                            </span></td>
                            <div class="modal fade" id="modalCekPembayaran{{$item->id}}">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4>Konfirmasi Pembayaran Donasi</h4>
                                        </div>
                                        <div class="modal-body">
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-sm-8 offset-sm-2">
                                                        <div class="form-row">
                                                            <div class="form-group col-md-6">
                                                                <label class="control-label">Nama User</label>
                                                                <input type="text" class="form-control"
                                                                    value="{{$item->getDonatur->name}}">
                                                            </div>
                                                            <div class="form-group col-md-6">
                                                                <label class="control-label">Order ID</label>
                                                                <input type="number" class="form-control" value="{{$item->id}}">
                                                            </div>
                                                        </div>
                                                        <div class="form-row">
                                                            <div class="form-group col-md-6">
                                                                <label class="control-label">Tgl. Masuk</label>
                                                                <input type="date" class="form-control"
                                                                    value="{{$item->tanggal_bayar}}">
                                                            </div>
                                                            <div class="form-group col-md-6">
                                                                <label class="control-label">Jumlah</label>
                                                                <input type="number" class="form-control"
                                                                    value="{{$item->jumlah}}">
                                                            </div>
                                                        </div>
                                                        <div class="form-row">
                                                            <div class="form-group col-md-6">
                                                                <label class="control-label">Ditujukan ke</label>
                                                                <input type="text" class="form-control"
                                                                    value="{{$item->getDifabel->name}}">
                                                            </div>
                                                        </div>
                                                        <div class="form-row">
                                                            <div class="form-group col-md-12">
                                                                <label class="control-label">Pesan Semangat</label>
                                                                <textarea class="form-control" rows="3">{{$item->pesan_semangat}}</textarea>
                                                            </div>
                                                        </div>
                                                        <div class="form-row">
                                                            <div class="form-group col-md-12">
                                                                <label class="control-label">Bukti Pembayaran</label>
                                                                <br>
                                                                <a href="{{ asset('foto_donasi/'.$item->bukti_pembayaran)}}" target="_blank">
                                                                    Lihat Bukti Pembayaran</a>
                                                            </div>
                                                        </div>
                                                        <form action="{{ route('admin.donasi.update')}}" method="POST">
                                                            @csrf
                                                            <input type="hidden" name="id" value="{{$item->id}}">
                                                        <div class="form-row">
                                                            <div class="form-group col-md-12">
                                                                <label class="control-label">Status</label>
                                                                <select class="form-control" name="status">
                                                                    <option value="1">Diterima</option>
                                                                    <option value="0">Dipending</option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="form-row">
                                                            <div class="col-sm-12">
                                                                <div class="text-center">
                                                                    <button type="submit" class="btn btn-gradient-success btn-full">Konfirmasi
                                                                        Pembayaran</button>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/admin/pembayaran/produk.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Transaksi Produk Terbaru</h4>
            </div>
            <div class="table-overflow container">
                <table class="table table-striped table-bordered datatable">
                    <thead>
                        <tr>
                            <td class="text-dark text-semibold">Nama User</td>
                            <td class="text-dark text-semibold">Order ID</td>
                            <td class="text-dark text-semibold">Tgl Masuk</td>
                            <td class="text-dark text-semibold">Jumlah</td>
                            <td class="text-dark text-semibold">Status</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($transaksi as $item)
                        <tr>
                            <td>
                                <div class="list-item">
                                    <div class="info">
                                        <span class="title p-t-10 text-semibold">{{$item->getUser->name}}</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <a href="javascript:void(0)" data-toggle="modal"
                                    data-target="#modalCekPembayaranProduk{{$item->id}}">
                                    #{{$item->id}}
                                </a>
                            </td>
                            <td>{{$item->tanggal_pembelian}}</td>
                            <td>{{$item->getTotal()}}</td>
                            <td><span class="badge badge-pill">
                                @if ($item->status == 0)
                                Pending
                                @else
                                Diterima
                                @endif
                            </span></td>
                        </tr>
                        <div class="modal fade" id="modalCekPembayaranProduk{{$item->id}}">
                            <div class="modal-dialog modal-lg" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4>Konfirmasi Pembayaran Produk</h4>
                                    </div>
                                    <div class="modal-body">
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-sm-8 offset-sm-2">
                                                    <div class="form-row">
                                                        <div class="form-group col-md-6">
                                                            <label class="control-label">Nama User</label>
                                                            <input type="text" class="form-control" value="{{$item->getUser->name}}">
                                                        </div>
                                                        <div class="form-group col-md-6">
                                                            <label class="control-label">Order ID</label>
                                                            <input type="number" class="form-control" value="#{{$item->id}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-4">
                                                            <label class="control-label">Total</label>
                                                            <input type="number" class="form-control" value="{{$item->getTotal()}}">
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="form-group col-md-12">
                                                            <label class="control-label">Bukti Pembayaran</label>
                                                            <br>
                                                            <a href="{{ asset('foto_pembayaran_produk/'.$item->bukti_pembayaran)}}" target="_blank"> Lihat
                                                                Bukti Pembayaran</a>

                                                        </div>
                                                    </div>
                                                    <form action="{{ route('admin.produk.update')}}" method="POST">
                                                        @csrf
                                                        <input type="hidden" name="id" value="{{$item->id}}">
                                                    <div class="form-row">
                                                        <div class="form-group col-md-12">
                                                            <label class="control-label">Status</label>
                                                            <select class="form-control" name="status">
                                                                <option value="1">Diterima</option>
                                                                <option value="0">Dipending</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                    <div class="form-row">
                                                        <div class="col-sm-12">
                                                            <div class="text-center">
                                                                <button type="submit" class="btn btn-gradient-success btn-full">Konfirmasi
                                                                    Pembayaran</button>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection